coin_whole_list=[
  'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT', 'DOGEUSDT', 'TRXUSDT',
  'TONUSDT', 'ADAUSDT', 'AVAXUSDT', '1000SHIBUSDT', 'DOTUSDT', 'LINKUSDT',
  'BCHUSDT', 'LTCUSDT', 'UNIUSDT', 'ATOMUSDT', 'MKRUSDT',
  'XLMUSDT', 'ETCUSDT', 'AAVEUSDT', 'VETUSDT', 'INJUSDT', 'HBARUSDT',
  'GRTUSDT', 'RUNEUSDT', 'FTMUSDT', 'ALGOUSDT', 'MATICUSDT', 'OPUSDT',
  'XTZUSDT', 'EOSUSDT', 'AXSUSDT', 'SANDUSDT', 'DYDXUSDT',
  'ENSUSDT', '1000XECUSDT', 'WLDUSDT', 'CFXUSDT', 'SUIUSDT',
  'STXUSDT', 'FILUSDT', 'IMXUSDT', 'XMRUSDT', 'APTUSDT', 'FETUSDT',
  '1000PEPEUSDT', 'KASUSDT', 'ICPUSDT', '1000FLOKIUSDT', '1000BONKUSDT',
  'JUPUSDT', 'PYTHUSDT', 'JASMYUSDT', 'SEIUSDT', 'BSVUSDT', 'TIAUSDT',
  'LDOUSDT', 'FLOWUSDT', 'NOTUSDT', 'EGLDUSDT',
  'NEOUSDT', 'GALAUSDT', 'YFIUSDT', 'TRBUSDT', 'RNDRUSDT', 'ARUSDT',
  'ILVUSDT', 'COMPUSDT', 'AIUSDT', 'IDUSDT', 'PORTALUSDT', 'KSMUSDT',
  'NMRUSDT', 'PEOPLEUSDT', 'RIFUSDT', 'MANAUSDT', 'ZILUSDT', 'WAXPUSDT',
  'GMTUSDT', 'CHRUSDT' , 'ZENUSDT','IOUSDT','BANDUSDT','REEFUSDT',
  'LSKUSDT','MAVIAUSDT','WIFUSDT','1000SATSUSDT',
  'BOMEUSDT','SUPERUSDT','LUNA2USDT','ARBUSDT'
]